In [1]:
import numpy as np


## Numpy is Numerical Python.
## It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# Numpy Functions

In [2]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# np.zeros

In [3]:
array2 = np.zeros((4,3) , dtype=int)   # Default dtype = float
array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## np.ones

In [4]:
array3 = np.ones((2,3) , dtype=int)
array3

array([[1, 1, 1],
       [1, 1, 1]])

## np.arange

In [5]:
array4 = np.arange(6,20,2)
array4

array([ 6,  8, 10, 12, 14, 16, 18])

## random

In [7]:
array6 = np.random.randint(0,30,size=(4,4))
print(array6)

[[20  2 24 28]
 [12 28 11  6]
 [ 4 12 17  6]
 [27 26  0  7]]


## np.full

In [9]:
array7 = np.full((3,2,2),6)
print(array7)

[[[6 6]
  [6 6]]

 [[6 6]
  [6 6]]

 [[6 6]
  [6 6]]]


In [11]:
a = np.random.randint(1,7,(2,4))
a

array([[4, 1, 1, 5],
       [3, 5, 5, 4]])

In [12]:
b = np.random.randint(5,10,(2,4))
b

array([[9, 6, 6, 9],
       [6, 6, 5, 8]])

## divide

In [14]:
divide = np.divide(105,5)
divide

21.0

## multiplication

In [15]:
multiply = np.multiply(158, 200)
multiply

31600

## Aggregation Operations

In [16]:
data = np.random.randint(1,16,(2,4))
data

array([[ 3, 13,  6,  6],
       [12, 10,  7,  4]])

## add

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)

In [18]:
c

array([5, 7, 9])

## subtract

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.subtract(a, b)

In [20]:
c

array([-3, -3, -3])

# Numpy array attributes

## ndarray.shape

* This returns a tuple consisting of array dimensions.

In [21]:
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1.shape)

(2, 3)


In [22]:
array_2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]])
print(array_2.shape)

(4, 2, 3)


## ndarray.ndim

* This returns the number of array dimensions.

In [23]:
array_3 = np.array([[1,2,3],[4,5,6]])
print(f"The dimension of array_3: ",array_3.ndim)

The dimension of array_3:  2


## ndarray.size

* This returns the total number of elements in the array

In [24]:
array_4 = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in array_4 =  {array_4.size}")

The total number of elements in array_4 =  6


## ndarray.dtype

* This returns the data type of the array

In [25]:
array_5 = np.array([1,2,3,4,5])
print(array_5.dtype)

int32


array_6 = np.array([1,2,3,4,5,5.678,-6])
print(array_6.dtype)

## ndarray.astype

* This changes the data type of an array.

In [27]:
array_7 = np.array([2,3,4])
print(array_7.dtype)
print(array_7)
array_7_ = array_7.astype('float64')
print(array_7_.dtype)
print(array_7_)

int32
[2 3 4]
float64
[2. 3. 4.]


# Array Manipulation

## np.transpose(array)

In [29]:
array_8 = np.array(np.random.randint(1,6,(5,2)))
array_8

array([[3, 4],
       [4, 1],
       [2, 4],
       [3, 1],
       [2, 2]])

In [33]:
transpose_arr = np.transpose(array_8)
transpose_arr

array([[3, 4, 2, 3, 2],
       [4, 1, 4, 1, 2]])

## np.reshape(array,shape)

* To Change shape of an array

In [34]:
array_9 = np.array(np.random.randint(1,6,(6,2)))
array_9

array([[3, 3],
       [3, 1],
       [1, 2],
       [4, 1],
       [4, 3],
       [4, 1]])

In [35]:
new_shape = (3,2,2)
reshaped_arr = np.reshape(array_9,new_shape)
reshaped_arr

array([[[3, 3],
        [3, 1]],

       [[1, 2],
        [4, 1]],

       [[4, 3],
        [4, 1]]])

## flatten

In [36]:
array_10 = np.array(np.random.randint(1,6,(6,2)))
array_10

array([[5, 2],
       [1, 2],
       [3, 1],
       [5, 1],
       [4, 1],
       [3, 1]])

In [37]:
array_10.flatten()

array([5, 2, 1, 2, 3, 1, 5, 1, 4, 1, 3, 1])